version: '3.7'


networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  app_1:
    container_name: app1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - monitor-net
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: curl --fail http://0.0.0.0:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  app_2:
    container_name: app2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - monitor-net
    command: python manage.py runserver 0.0.0.0:8080
    healthcheck:
      test: curl --fail http://0.0.0.0:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - monitor-net

      
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
    networks:
      - monitor-net
      
  
volumes:
  grafana-data:
  grafana-configs:

   
      
